### PR TITLE
add password protection

### PR DESCRIPTION
**Pull request by mcgoooo**
couldn't find a cleaner way of doing this

### CODE REVIEW

**Comment by robinwhittleton** [comment]
Are there any sane tests we can write for this functionality?

**Comment by tvararu** [comment]
@robinwhittleton I'm thinking this needs an end to end test.

From attempting to hack an example of what that could be like, it became apparent that maybe the username and password should be specified in some form of constructor to allow easier initialisation using the programatic API.

Rough pseudocode of a minimally viable test case:

```javascript
// Seems like Chai is used in the other tests.
const chai = require('chai')
const expect  = chai.expect;
const fractalServer = require('../src/web/server')
const request = require('request') // Or superagent, et al

describe('server password protection', () => {
  before(() => {
    // Start the server on port 5000 and don't use browser sync.
    // The third argument doesn't exist; I haven't looked into the full API
    // of Fractal but substitute it with some other constructor or way of initialising
    // those values which default to env vars if they're not defined.
    fractalServer(5000, false, {
      username: 'admin',
      password: 'rosebud'
    })
  })

  it('should reject requests that don\'t have auth', (done) => {
    request('http://localhost:5000/', (error, response, body) => {
      expect(response.status).to.equal(401)
      done()
    })
  })
  
  it('should work with requests that have auth', (done) => {
    request('http://admin:rosebud@localhost:5000/', (error, response, body) => {
      expect(response.status).to.equal(200)
      done()
    })
  })
})
```

**Comment by mcgoooo** [comment]
@tvararu agreed, there is also this feature request, so it may be good conversing with them how they may wish to handle it

**Comment by mcgoooo** [comment]
https://github.com/frctl/fractal/issues/186

**Comment by fofr** [comment]
Should this be closed?

**Comment by mcgoooo** [comment]
i reckon so, the pull is always here for reference

**Pull request closed without merging**
